### ISSUE TITLE
Remove kafka offset exception while docker running

### ISSUE THREAD

**Issue by stingion** [makeitfine-org/mif#8]

**Comment by stingion** [comment]
2020-08-29 14:19:12.239 ERROR [kafka,,,] 23654 --- [extShutdownHook] kafka.server.LogDirFailureChannel        : Error while writing to checkpoint file /tmp/kafka-15913803789264534634/replication-offset-checkpoint

java.io.FileNotFoundException: /tmp/kafka-15913803789264534634/replication-offset-checkpoint.tmp (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method) ~[na:na]
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298) ~[na:na]
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[na:na]
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[na:na]
        at kafka.server.checkpoints.CheckpointFile.liftedTree1$1(CheckpointFile.scala:52) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:50) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:59) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$9(ReplicaManager.scala:1439) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$9$adapted(ReplicaManager.scala:1439) ~[kafka_2.12-2.3.0.jar:na]
        at scala.Option.foreach(Option.scala:274) ~[scala-library-2.12.8.jar:na]
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$7(ReplicaManager.scala:1439) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$7$adapted(ReplicaManager.scala:1436) ~[kafka_2.12-2.3.0.jar:na]
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:792) ~[scala-library-2.12.8.jar:na]
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:128) ~[scala-library-2.12.8.jar:na]
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:791) ~[scala-library-2.12.8.jar:na]
        at kafka.server.ReplicaManager.checkpointHighWatermarks(ReplicaManager.scala:1436) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.ReplicaManager.shutdown(ReplicaManager.scala:1518) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.KafkaServer.$anonfun$shutdown$16(KafkaServer.scala:624) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:88) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.KafkaServer.shutdown(KafkaServer.scala:624) ~[kafka_2.12-2.3.0.jar:na]
        at org.springframework.kafka.test.EmbeddedKafkaBroker.destroy(EmbeddedKafkaBroker.java:384) ~[spring-kafka-test-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1072) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1065) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1060) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1029) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]

2020-08-29 14:19:12.241 ERROR [kafka,,,] 23654 --- [extShutdownHook] kafka.server.ReplicaManager              : [ReplicaManager broker=0] Error while writing to highwatermark file in directory /tmp/kafka-15913803789264534634

org.apache.kafka.common.errors.KafkaStorageException: Error while writing to checkpoint file /tmp/kafka-15913803789264534634/replication-offset-checkpoint
Caused by: java.io.FileNotFoundException: /tmp/kafka-15913803789264534634/replication-offset-checkpoint.tmp (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method) ~[na:na]
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298) ~[na:na]
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[na:na]
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[na:na]
        at kafka.server.checkpoints.CheckpointFile.liftedTree1$1(CheckpointFile.scala:52) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:50) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:59) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$9(ReplicaManager.scala:1439) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$9$adapted(ReplicaManager.scala:1439) ~[kafka_2.12-2.3.0.jar:na]
        at scala.Option.foreach(Option.scala:274) ~[scala-library-2.12.8.jar:na]
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$7(ReplicaManager.scala:1439) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$7$adapted(ReplicaManager.scala:1436) ~[kafka_2.12-2.3.0.jar:na]
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:792) ~[scala-library-2.12.8.jar:na]
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:128) ~[scala-library-2.12.8.jar:na]
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:791) ~[scala-library-2.12.8.jar:na]
        at kafka.server.ReplicaManager.checkpointHighWatermarks(ReplicaManager.scala:1436) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.ReplicaManager.shutdown(ReplicaManager.scala:1518) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.KafkaServer.$anonfun$shutdown$16(KafkaServer.scala:624) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:88) ~[kafka_2.12-2.3.0.jar:na]
        at kafka.server.KafkaServer.shutdown(KafkaServer.scala:624) ~[kafka_2.12-2.3.0.jar:na]
        at org.springframework.kafka.test.EmbeddedKafkaBroker.destroy(EmbeddedKafkaBroker.java:384) ~[spring-kafka-test-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1072) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1065) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1060) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1029) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]

2020-08-29 14:19:12.241  INFO [kafka,,,] 23654 --- [extShutdownHook] kafka.server.ReplicaManager              : [ReplicaManager broker=0] Shut down completely
2020-08-29 14:19:12.242  INFO [kafka,,,] 23654 --- [extShutdownHook] kafka.log.LogManager                     : Shutting down.
2020-08-29 14:19:12.243  INFO [kafka,,,] 23654 --- [extShutdownHook] kafka.log.LogCleaner                     : Shutting down the log cleaner.
2020-08-29 14:19:12.243  INFO [kafka,,,] 23654 --- [extShutdownHook] kafka.log.LogCleaner                     : [kafka-log-cleaner-thread-0]: Shutting down
2020-08-29 14:19:12.243  INFO [kafka,,,] 23654 --- [leaner-thread-0] kafka.log.LogCleaner                     : [kafka-log-cleaner-thread-0]: Stopped
2020-08-29 14:19:12.243  INFO [kafka,,,] 23654 --- [extShutdownHook] kafka.log.LogCleaner                     : [kafka-log-cleaner-thread-0]: Shutdown completed
2020-08-29 14:19:12.304  INFO [kafka,,,] 23654 --- [pool-8-thread-1] kafka.log.ProducerStateManager           : [ProducerStateManager partition=test_topic-0] Writing producer snapshot at offset 1
